---
title: "path"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
```

## import data 
```{r import_data}
read_as_df <- function(path, col_name) {
  df <- read.csv(path, header = FALSE) %>% data.frame()
  names(df) <- col_name
  return(df)
}

points <- read.csv("data/cpp_astar_path.csv")
points_pick_reg <- read.csv("data/cpp_reg_simplified.csv")
three_d_map <- read.csv("data/status.csv")

head(points)
points_pick_reg
```

## plot using plotly package
```{r plotly, warning=FALSE}
print_points <- function(input_df){
  return (input_df %>% 
            plot_ly() %>% 
            add_paths(x = ~x, y = ~y, z = ~z))
}

print_points(points)
print_points(points_pick_reg)

```


## visiualization with searched areas and blocked areas.
```{r mesh, warning=FALSE}
print_3D_model_path <- function(map_df, path_df, block_status = 1, searched_status = 2) {
  map_block <- map_df %>% filter(status == block_status)
  map_searched <- map_df %>% filter(status == searched_status)
  p <- plot_ly() %>%
  # draw blocked
  add_trace(type="scatter3d", mode = 'markers', ids = 'blocks',
            x = map_block$x, y = map_block$y, z = map_block$z, 
            marker = list(color = c('#696969'), 
                          symbol = 'square', size = '2', opacity = '0.5')) %>% 
  # draw searched
  add_trace(type="scatter3d", mode = 'markers', ids = 'blocks',
            x = map_searched$x, y = map_searched$y, z = map_searched$z, 
            marker = list(color = c('#66ccff'), 
                          symbol = 'square', size = '0.2', opacity = '1')) %>% 
  
  add_paths(x = path_df$x, y = path_df$y, z = path_df$z,
            line = list(width = 10, color = '#FF0000'))
  p
}

print_3D_model_path(three_d_map, points_pick_reg)

```